name = "paygate-site"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]

# Make Cloudflare treat this as a Pages project output.
pages_build_output_dir = ".vercel/output/static"
